name: CI
on: push
jobs:
  code-check:
    name: Lint and Format

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: '12.22.7'
        os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn lint
      - run: yarn format:check

  test:
    name: Test suite

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: '12.22.7'
        os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn test --ci --verbose --coverage --maxWorkers=2

  build:
    name: Trying to build
    needs: test
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: '12.22.7'
        os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn build
