name: CI
on: push
jobs:
  code-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12.22.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn format:check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12.22.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test --ci --verbose --maxWorkers=50%

  build:
    needs: test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12.22.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
